apiVersion: v1
kind: Service
metadata:
  name: persona-service
  namespace: default
  labels:
    app: ai-travel-platform
    component: persona-service
    version: v1
    part-of: ai-travel-platform
    managed-by: kubernetes
  annotations:
    # Prometheus metrics collection configuration
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
    # Enable topology-aware routing for better performance
    service.kubernetes.io/topology-aware-hints: "auto"
    # Service documentation
    description: "AI Persona Service for managing ML-powered travel personas"
    maintainer: "platform-team@company.com"
spec:
  # Using ClusterIP for internal service mesh access
  type: ClusterIP
  ports:
    # Main application port
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
      appProtocol: http
    # Metrics port for Prometheus scraping
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics
      appProtocol: http
  # Selector matching deployment pod labels
  selector:
    app: ai-travel-platform
    component: persona-service
  # Session handling configuration
  sessionAffinity: None
  # Internal traffic policy for cluster routing
  internalTrafficPolicy: Cluster
  # IP family configuration
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4