apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-travel-platform-config
  namespace: default
  labels:
    app: ai-travel-platform
    environment: ${NODE_ENV}
    version: 1.0.0
  annotations:
    description: "Base configuration for AI Travel Platform services"
    lastUpdated: "2024-01-20"
    maintainer: "platform-team@company.com"
data:
  # Common Configuration
  # Controls environment-specific behavior and logging
  NODE_ENV: "development"
  LOG_LEVEL: "info"
  SERVICE_MESH_ENABLED: "true"
  TRACING_ENABLED: "true"
  MONITORING_ENABLED: "true"

  # Database Configuration
  # PostgreSQL connection settings with security and performance tuning
  DB_HOST: "postgres-primary.default.svc.cluster.local"
  DB_PORT: "5432"
  DB_USERNAME: "app_user"
  DB_DATABASE: "travel_platform"
  DB_SSL: "true"
  DB_CONNECTION_POOL_SIZE: "10"
  DB_IDLE_TIMEOUT: "10000"

  # WebSocket Configuration
  # Real-time communication settings for social features
  WEBSOCKET_PORT: "3001"
  PING_TIMEOUT: "5000"
  PING_INTERVAL: "25000"
  MAX_BUFFER_SIZE: "10485760"  # 10MB in bytes
  SOCKET_KEEPALIVE: "true"
  MAX_CONNECTIONS: "10000"

  # ML Service Configuration
  # AI model serving and inference settings
  ML_CONFIG_PATH: "/etc/ml/config"
  MODEL_SERVING_PORT: "5000"
  MODEL_UPDATE_INTERVAL: "3600"  # 1 hour in seconds
  INFERENCE_TIMEOUT: "5000"      # 5 seconds
  MODEL_CACHE_SIZE: "1024"       # Cache size in MB
  BATCH_SIZE: "32"

  # API Gateway Configuration
  # Security and request handling settings
  RATE_LIMIT_WINDOW: "60000"     # 1 minute in milliseconds
  RATE_LIMIT_MAX_REQUESTS: "1000"
  JWT_PUBLIC_KEY_PATH: "/etc/jwt/public.key"
  CORS_ALLOWED_ORIGINS: "https://*.company.com"
  MAX_REQUEST_SIZE: "10mb"
  REQUEST_TIMEOUT: "30000"       # 30 seconds

  # Health Check Configuration
  # Kubernetes probe endpoints and monitoring
  HEALTH_CHECK_PORT: "8080"
  HEALTH_CHECK_PATH: "/health"
  READINESS_CHECK_PATH: "/ready"
  LIVENESS_CHECK_PATH: "/live"

  # Service Discovery
  # Service mesh and registry configuration
  SERVICE_REGISTRY_URL: "http://consul:8500"
  SERVICE_REGISTRY_ENABLED: "true"
  SERVICE_NAME_PREFIX: "ai-travel"
  SERVICE_CHECK_INTERVAL: "10s"