# Kubernetes Secrets manifest for AI-Enhanced Social Travel Platform
# Version: 1.0.0
# Requires: sealed-secrets-controller v0.19.0
# Security Tier: High
# Rotation Schedule: 30 days

apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: ai-travel-platform
  labels:
    app: ai-travel-platform
    managed-by: sealed-secrets
    environment: ${ENV}
    security-tier: high
    created-by: platform-admin
    version: "1.0.0"
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    auth.ai-travel-platform.io/rotation-schedule: "30d"
    security.ai-travel-platform.io/encryption: "aes256-gcm"
    backup.ai-travel-platform.io/enabled: "true"
    security.ai-travel-platform.io/last-rotated: "${CURRENT_DATE}"
    security.ai-travel-platform.io/compliance: "pci-dss,gdpr,soc2"
    security.ai-travel-platform.io/access-control: "rbac-restricted"
type: Opaque
data:
  # Authentication Secrets
  JWT_SECRET: ${JWT_SECRET}
  JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
  API_KEYS: ${API_KEYS}
  MFA_SECRET: ${MFA_SECRET}

  # Database Credentials
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  REDIS_USERNAME: ${REDIS_USERNAME}
  REDIS_PASSWORD: ${REDIS_PASSWORD}

  # External Service Integration Secrets
  AMADEUS_API_KEY: ${AMADEUS_API_KEY}
  AMADEUS_API_SECRET: ${AMADEUS_API_SECRET}
  STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
  TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}

  # ML Service Credentials
  ML_MODEL_ACCESS_KEY: ${ML_MODEL_ACCESS_KEY}
  ML_MODEL_SECRET_KEY: ${ML_MODEL_SECRET_KEY}

  # Encryption Keys
  ENCRYPTION_KEY: ${ENCRYPTION_KEY}
  BACKUP_ENCRYPTION_KEY: ${BACKUP_ENCRYPTION_KEY}

---
# Metadata for Secret Rotation and Validation
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-metadata
  namespace: ai-travel-platform
  labels:
    app: ai-travel-platform
    component: secret-management
data:
  rotation-policy: |
    {
      "schedule": "0 0 */30 * *",
      "notification-threshold": "7d",
      "backup-retention": "90d",
      "emergency-contacts": [
        "security-team@ai-travel-platform.io",
        "devops-oncall@ai-travel-platform.io"
      ]
    }
  validation-rules: |
    {
      "min-length": 32,
      "complexity-requirements": {
        "special-chars": true,
        "numbers": true,
        "uppercase": true,
        "lowercase": true
      },
      "encryption-requirements": {
        "algorithm": "AES-256-GCM",
        "key-rotation": true,
        "secure-storage": true
      }
    }